name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Create Release
        uses: chiemerieezechukwu/semantic-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
          pre-release-script: |
            "GITHUB_TOKEN=${{ secrets.RELEASE_PAT }} ./scripts/pre-release.sh ${nextRelease.version}"
